### ISSUE TITLE
panic: runtime error: slice bounds out of range [:-1]

### ISSUE THREAD

**Issue by jametller** [mdempsky/gocode#118]
### What version of Go are you using (`go version`)?
1.13.5

### What operating system and processor architecture are you using (`go env`)?
Debian (Testing)
<pre>Linux j1nior 5.3.0-3-amd64 #1 SMP Debian 5.3.15-1 (2019-12-07) x86_64 GNU/Linux
</pre>

### What is the debug output of `gocode`?
~$ gocode -s debug
panic: runtime error: slice bounds out of range [:-1]

goroutine 10 [running]:
runtime/debug.Stack(0x37, 0x0, 0x0)
	/usr/lib/go-1.13/src/runtime/debug/stack.go:24 +0x9d
runtime/debug.PrintStack()
	/usr/lib/go-1.13/src/runtime/debug/stack.go:16 +0x22
main.(*Server).AutoComplete.func1(0xc00000fb20)
	/home/joan/go/src/github.com/mdempsky/gocode/server.go:79 +0xac
panic(0x9364a0, 0xc000028ec0)
	/usr/lib/go-1.13/src/runtime/panic.go:679 +0x1b2
github.com/mdempsky/gocode/internal/suggest.(*candidateCollector).qualify(0xc0000c50a0, 0xc0000b4820, 0xc0000b4a00, 0xc0000cd128)
	/home/joan/go/src/github.com/mdempsky/gocode/internal/suggest/candidate.go:186 +0x178
go/types.writePackage(0xc000113a70, 0xc0000b4820, 0xc0001ab598)
	/usr/lib/go-1.13/src/go/types/object.go:437 +0x82
go/types.writeType(0xc000113a70, 0xa2aa00, 0xc000113140, 0xc0001ab598, 0xc0001ab490, 0x2, 0x8)
	/usr/lib/go-1.13/src/go/types/typestring.go:233 +0xbe6
go/types.writeTuple(0xc000113a70, 0xc00035e000, 0xc0001ab301, 0xc0001ab598, 0xc0001ab490, 0x1, 0x8)
	/usr/lib/go-1.13/src/go/types/typestring.go:275 +0x172
go/types.writeSignature(0xc000113a70, 0xc000113200, 0xc0001ab598, 0xc0001ab490, 0x1, 0x8)
	/usr/lib/go-1.13/src/go/types/typestring.go:290 +0x6d
go/types.writeType(0xc000113a70, 0xa2aa80, 0xc000113200, 0xc0001ab598, 0xc0001ab490, 0x1, 0x8)
	/usr/lib/go-1.13/src/go/types/typestring.go:144 +0x649
go/types.WriteType(...)
	/usr/lib/go-1.13/src/go/types/typestring.go:75
go/types.TypeString(0xa2aa80, 0xc000113200, 0xc0001ab598, 0x4, 0x0)
	/usr/lib/go-1.13/src/go/types/typestring.go:67 +0xb1
github.com/mdempsky/gocode/internal/suggest.(*candidateCollector).asCandidate(0xc0000c50a0, 0xa38b80, 0xc0000b5bd0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/joan/go/src/github.com/mdempsky/gocode/internal/suggest/candidate.go:124 +0x3a5
github.com/mdempsky/gocode/internal/suggest.(*candidateCollector).getCandidates(0xc0000c50a0, 0xc0000b4690, 0x0, 0xc0000c50a0)
	/home/joan/go/src/github.com/mdempsky/gocode/internal/suggest/candidate.go:98 +0xc2
github.com/mdempsky/gocode/internal/suggest.(*Config).Suggest(0xc00000fb60, 0xc000030280, 0x41, 0xc0000302d0, 0x47, 0x47, 0x46, 0xc0000b44b0, 0x906ca0, 0xc000053b40, ...)
	/home/joan/go/src/github.com/mdempsky/gocode/internal/suggest/suggest.go:105 +0x31f
main.(*Server).AutoComplete(0xc00010200d, 0xc0000d4d00, 0xc00000fb20, 0x0, 0x0)
	/home/joan/go/src/github.com/mdempsky/gocode/server.go:128 +0x49d
reflect.Value.call(0xc000106060, 0xc000116020, 0x13, 0x973c29, 0x4, 0xc000053f18, 0x3, 0x3, 0xa31c20, 0xc000112690, ...)
	/usr/lib/go-1.13/src/reflect/value.go:460 +0x5f6
reflect.Value.Call(0xc000106060, 0xc000116020, 0x13, 0xc000047718, 0x3, 0x3, 0xc000048a80, 0x28, 0x30)
	/usr/lib/go-1.13/src/reflect/value.go:321 +0xb4
net/rpc.(*service).call(0xc0000fe140, 0xc000122000, 0xc000024a30, 0xc000024a40, 0xc000184000, 0xc0001140c0, 0x8a1a80, 0xc0000d4d00, 0x16, 0x8a1a40, ...)
	/usr/lib/go-1.13/src/net/rpc/server.go:377 +0x16f
created by net/rpc.(*Server).ServeCodec
	/usr/lib/go-1.13/src/net/rpc/server.go:474 +0x42b

### What (client-side) flags are you passing into `gocode`?

I do not execute it directly but using atom editor and autocomplete plugin.

### What editor are using?

atom

**Comment by jametller** [comment]
Btw, the panic does not happen with any big or strange file. It is a void main code and I try to autocomplete fmt.

**Comment by jametller** [comment]
I found the issue. The problem was that I had:

import fmt 
instead of:
import "fmt"

and that caused the crash when trying to autocomplete fmt. For me the issue can be closed, but maybe this case can be handled to avoid crashing.

Thank you for your project anyway!
