### ISSUE TITLE
panic: types.Named.SetUnderlying: underlying type must not be *Named

### ISSUE THREAD

**Issue by danp** [mdempsky/gocode#14]
Getting this with latest Go tip:

```
panic: types.Named.SetUnderlying: underlying type must not be *Named

goroutine 21 [running]:
runtime/debug.Stack(0xb, 0xc42046a218, 0x1)
    /Users/dan.peterson/Projects/go/project/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
    /Users/dan.peterson/Projects/go/project/go/src/runtime/debug/stack.go:16 +0x22
main.(*Server).AutoComplete.func1(0xc420192200)
    /Users/dan.peterson/Projects/go/src/github.com/mdempsky/gocode/server.go:69 +0x9e
panic(0x3edf40, 0xc4201f3d40)
    /Users/dan.peterson/Projects/go/project/go/src/runtime/panic.go:458 +0x243
go/types.(*Checker).handleBailout(0xc4200d0380, 0xc42046b440)
    /Users/dan.peterson/Projects/go/project/go/src/go/types/check.go:213 +0xae
panic(0x3edf40, 0xc4201f3d40)
    /Users/dan.peterson/Projects/go/project/go/src/runtime/panic.go:458 +0x243
go/types.(*Named).SetUnderlying(0xc420209530, 0x672de0, 0xc42014a2d0)
    /Users/dan.peterson/Projects/go/project/go/src/go/types/type.go:418 +0x95
go/internal/gcimporter.(*importer).typ(0xc4202a0000, 0x0, 0x2b819a, 0xc4202a0000)
    /Users/dan.peterson/Projects/go/project/go/src/go/internal/gcimporter/bimport.go:287 +0x274
go/internal/gcimporter.(*importer).obj(0xc4202a0000, 0xfffffffffffffffd)
    /Users/dan.peterson/Projects/go/project/go/src/go/internal/gcimporter/bimport.go:187 +0x74f
go/internal/gcimporter.BImportData(0xc4201569c0, 0xc4202b8000, 0x3b46a, 0x3fe00, 0xc420196281, 0x30, 0x0, 0x30, 0x0, 0x1200000000)
    /Users/dan.peterson/Projects/go/project/go/src/go/internal/gcimporter/bimport.go:86 +0x34c
go/internal/gcimporter.Import(0xc4201569c0, 0xc420196281, 0x30, 0xc4200c72d0, 0x64, 0x0, 0x0, 0x0)
    /Users/dan.peterson/Projects/go/project/go/src/go/internal/gcimporter/gcimporter.go:166 +0x551
go/importer.gcimports.ImportFrom(0xc4201569c0, 0xc420196281, 0x30, 0xc4200c72d0, 0x64, 0x0, 0x30, 0xc41ffdf122, 0xc420276c00)
    /Users/dan.peterson/Projects/go/project/go/src/go/importer/importer.go:70 +0x67
github.com/mdempsky/gocode/gbimporter.(*importer).ImportFrom(0xc420196100, 0xc420196281, 0x30, 0xc4200c72d0, 0x64, 0x0, 0x0, 0x0, 0x0)
    /Users/dan.peterson/Projects/go/src/github.com/mdempsky/gocode/gbimporter/gbimporter.go:82 +0x35d
go/types.(*Checker).collectObjects(0xc4200d0380)
    /Users/dan.peterson/Projects/go/project/go/src/go/types/resolver.go:191 +0x81d
go/types.(*Checker).checkFiles(0xc4200d0380, 0xc420086660, 0x1, 0x1, 0x0, 0x0)
    /Users/dan.peterson/Projects/go/project/go/src/go/types/check.go:225 +0xaa
go/types.(*Checker).Files(0xc4200d0380, 0xc420086660, 0x1, 0x1, 0xc4201c0c60, 0xc42018d4c8)
    /Users/dan.peterson/Projects/go/project/go/src/go/types/check.go:218 +0x49
go/types.(*Config).Check(0xc4201bd640, 0x0, 0x0, 0xc420196140, 0xc420086660, 0x1, 0x1, 0xc4201c2460, 0xc4201c4c40, 0x8, ...)
    /Users/dan.peterson/Projects/go/project/go/src/go/types/api.go:344 +0x19f
github.com/mdempsky/gocode/suggest.(*Suggester).analyzePackage(0xc42046b8b3, 0xf581d8, 0xc420196100, 0xc4200c72d0, 0x6c, 0xc420198000, 0x1c6d, 0x1c6d, 0x1398, 0x0, ...)
    /Users/dan.peterson/Projects/go/src/github.com/mdempsky/gocode/suggest/suggest.go:110 +0x6bc
github.com/mdempsky/gocode/suggest.(*Suggester).Suggest(0xc42046b8b3, 0xf581d8, 0xc420196100, 0xc4200c72d0, 0x6c, 0xc420198000, 0x1c6d, 0x1c6d, 0x1398, 0x0, ...)
    /Users/dan.peterson/Projects/go/src/github.com/mdempsky/gocode/suggest/suggest.go:37 +0xcf
main.(*Server).AutoComplete(0x6b5a38, 0xc420104c30, 0xc420192200, 0x0, 0x0)
    /Users/dan.peterson/Projects/go/src/github.com/mdempsky/gocode/server.go:89 +0x188
reflect.Value.call(0xc420164300, 0xc42014e038, 0x13, 0x486b08, 0x4, 0xc42046bec0, 0x3, 0x3, 0x13d38, 0x0, ...)
    /Users/dan.peterson/Projects/go/project/go/src/reflect/value.go:434 +0x5c9
reflect.Value.Call(0xc420164300, 0xc42014e038, 0x13, 0xc42046bec0, 0x3, 0x3, 0x9, 0x9, 0x1000)
    /Users/dan.peterson/Projects/go/project/go/src/reflect/value.go:302 +0xa4
net/rpc.(*service).call(0xc420152340, 0xc420152100, 0xc4200758d0, 0xc420170180, 0xc420103820, 0x3de2e0, 0xc420104c30, 0x16, 0x3de2a0, 0xc420192200, ...)
    /Users/dan.peterson/Projects/go/project/go/src/net/rpc/server.go:383 +0x148
created by net/rpc.(*Server).ServeCodec
    /Users/dan.peterson/Projects/go/project/go/src/net/rpc/server.go:477 +0x421
```

**Comment by mdempsky** [comment]
Do you have a repro case?

**Comment by danp** [comment]
Trying to get one. Naturally, when I tweaked Suggester to wrap importer with something that does debugging the issue went away.

**Comment by mdempsky** [comment]
Is it possible your cmd/compile, go/types, and/or github.com/mdempsky/gocode builds were out of sync?

**Comment by danp** [comment]
I don't think so. Just did my normal `git pull && GOROOT_BOOTSTRAP=~/Projects/go/go1.4 ./make.bash` flow in my tip src directory.

And I can reliably fix it by changing to [this branch](https://github.com/mdempsky/gocode/compare/master...dpiddy:debug) and running `go install ./...`. If I change back to master and install again it breaks again. So perhaps something cares about the importer being used?

**Comment by danp** [comment]
(And sorry, the code that is triggering the panic is internal so I can't share it. Trying to figure out what about it is triggering the problem so I can create a repro.)

**Comment by mdempsky** [comment]
It looks like your debugImporter doesn't implement [go/types.ImporterFrom](https://golang.org/pkg/go/types/#ImporterFrom).  Perhaps try that?

**Comment by danp** [comment]
Ah, yes. Did that and may have something. Will report back soon.

**Comment by danp** [comment]
Fortunately it's happening with an open source package. [Here](https://gist.github.com/dpiddy/4746baec4b8d0948fb8ccd436004df81) is a repro. I did a `go get -u github.com/sclasen/swfsm/fsm` and now if I try to edit this file and complete anything it panics.

**Comment by danp** [comment]
Happy to dig further if you have any suggestions on how to proceed or why this package would be problematic.

**Comment by danp** [comment]
And for completeness here is the output:

```
2016/06/01 14:59:30 fn=ImportFrom path="github.com/sclasen/swfsm/fsm" srcDir="/Users/dan.peterson/Projects/go/src/github.com/dpiddy/gocode-repro" mode=0 at=start
panic: types.Named.SetUnderlying: underlying type must not be *Named

goroutine 70 [running]:
runtime/debug.Stack(0xb, 0xc4201bdf30, 0x1)
    /Users/dan.peterson/Projects/go/project/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
    /Users/dan.peterson/Projects/go/project/go/src/runtime/debug/stack.go:16 +0x22
main.(*Server).AutoComplete.func1(0xc4200e7ec0)
    /Users/dan.peterson/Projects/go/src/github.com/mdempsky/gocode/server.go:69 +0x9e
panic(0x3ee9c0, 0xc420017d20)
    /Users/dan.peterson/Projects/go/project/go/src/runtime/panic.go:458 +0x243
go/types.(*Checker).handleBailout(0xc4200b8620, 0xc4201bf428)
    /Users/dan.peterson/Projects/go/project/go/src/go/types/check.go:213 +0xae
panic(0x3ee9c0, 0xc420017d20)
    /Users/dan.peterson/Projects/go/project/go/src/runtime/panic.go:458 +0x243
go/types.(*Named).SetUnderlying(0xc420137740, 0x672e20, 0xc420130540)
    /Users/dan.peterson/Projects/go/project/go/src/go/types/type.go:418 +0x95
go/internal/gcimporter.(*importer).typ(0xc420190000, 0x0, 0xc420484000, 0xf00000)
    /Users/dan.peterson/Projects/go/project/go/src/go/internal/gcimporter/bimport.go:287 +0x274
go/internal/gcimporter.(*importer).param(0xc420190000, 0x0, 0x1, 0xc420147cf8)
    /Users/dan.peterson/Projects/go/project/go/src/go/internal/gcimporter/bimport.go:524 +0x49
go/internal/gcimporter.(*importer).paramList(0xc420190000, 0x0, 0xc420017d00)
    /Users/dan.peterson/Projects/go/project/go/src/go/internal/gcimporter/bimport.go:518 +0xb2
go/internal/gcimporter.(*importer).obj(0xc420190000, 0xfffffffffffffffb)
    /Users/dan.peterson/Projects/go/project/go/src/go/internal/gcimporter/bimport.go:199 +0x38a
go/internal/gcimporter.BImportData(0xc4202523f0, 0xc420264000, 0xb11de, 0xffe00, 0xc4200e7f61, 0x1c, 0x0, 0x1c, 0x239745, 0x1200000004)
    /Users/dan.peterson/Projects/go/project/go/src/go/internal/gcimporter/bimport.go:86 +0x34c
go/internal/gcimporter.Import(0xc4202523f0, 0xc4200e7f61, 0x1c, 0xc420164870, 0x42, 0x0, 0x0, 0x0)
    /Users/dan.peterson/Projects/go/project/go/src/go/internal/gcimporter/gcimporter.go:166 +0x551
go/importer.gcimports.ImportFrom(0xc4202523f0, 0xc4200e7f61, 0x1c, 0xc420164870, 0x42, 0x0, 0x53d20, 0xc42013e000, 0xc4204a0b00)
    /Users/dan.peterson/Projects/go/project/go/src/go/importer/importer.go:70 +0x67
github.com/mdempsky/gocode/gbimporter.(*importer).ImportFrom(0xc420011d40, 0xc4200e7f61, 0x1c, 0xc420164870, 0x42, 0x0, 0x0, 0x0, 0x0)
    /Users/dan.peterson/Projects/go/src/github.com/mdempsky/gocode/gbimporter/gbimporter.go:82 +0x35d
github.com/mdempsky/gocode/suggest.(*debugImporter).ImportFrom(0xc420132350, 0xc4200e7f61, 0x1c, 0xc420164870, 0x42, 0x0, 0x0, 0x1, 0x0)
    /Users/dan.peterson/Projects/go/src/github.com/mdempsky/gocode/suggest/suggest.go:142 +0x1ec
go/types.(*Checker).collectObjects(0xc4200b8620)
    /Users/dan.peterson/Projects/go/project/go/src/go/types/resolver.go:191 +0x81d
go/types.(*Checker).checkFiles(0xc4200b8620, 0xc420147eb0, 0x1, 0x1, 0x0, 0x0)
    /Users/dan.peterson/Projects/go/project/go/src/go/types/check.go:225 +0xaa
go/types.(*Checker).Files(0xc4200b8620, 0xc420147eb0, 0x1, 0x1, 0xc4202526f0, 0xc4200514c0)
    /Users/dan.peterson/Projects/go/project/go/src/go/types/check.go:218 +0x49
go/types.(*Config).Check(0xc4204c8140, 0x0, 0x0, 0xc420011d80, 0xc420147eb0, 0x1, 0x1, 0xc420164d20, 0xc420a12200, 0x26, ...)
    /Users/dan.peterson/Projects/go/project/go/src/go/types/api.go:344 +0x19f
github.com/mdempsky/gocode/suggest.(*Suggester).analyzePackage(0xc4201bf8b3, 0xf900e0, 0xc420011d40, 0xc420164870, 0x4a, 0xc42009a980, 0x7a, 0x7a, 0x55, 0x1, ...)
    /Users/dan.peterson/Projects/go/src/github.com/mdempsky/gocode/suggest/suggest.go:110 +0x6cf
github.com/mdempsky/gocode/suggest.(*Suggester).Suggest(0xc4201bf8b3, 0xf900e0, 0xc420011d40, 0xc420164870, 0x4a, 0xc42009a980, 0x7a, 0x7a, 0x55, 0x0, ...)
    /Users/dan.peterson/Projects/go/src/github.com/mdempsky/gocode/suggest/suggest.go:37 +0xcf
main.(*Server).AutoComplete(0x6b5a78, 0xc4200e8340, 0xc4200e7ec0, 0x0, 0x0)
    /Users/dan.peterson/Projects/go/src/github.com/mdempsky/gocode/server.go:89 +0x188
reflect.Value.call(0xc420072780, 0xc42002e3c0, 0x13, 0x487688, 0x4, 0xc4201bfec0, 0x3, 0x3, 0x13d38, 0x0, ...)
    /Users/dan.peterson/Projects/go/project/go/src/reflect/value.go:434 +0x5c9
reflect.Value.Call(0xc420072780, 0xc42002e3c0, 0x13, 0xc4201bfec0, 0x3, 0x3, 0x9, 0x9, 0x1000)
    /Users/dan.peterson/Projects/go/project/go/src/reflect/value.go:302 +0xa4
net/rpc.(*service).call(0xc42014a080, 0xc420011e40, 0xc420141ba8, 0xc42009a800, 0xc4201420a0, 0x3ded60, 0xc4200e8340, 0x16, 0x3ded20, 0xc4200e7ec0, ...)
    /Users/dan.peterson/Projects/go/project/go/src/net/rpc/server.go:383 +0x148
created by net/rpc.(*Server).ServeCodec
    /Users/dan.peterson/Projects/go/project/go/src/net/rpc/server.go:477 +0x421
```

**Comment by mdempsky** [comment]
This looks like a go/types bug.  I can repro running just gotype on your test case.  Will report upstream.

**Comment by mdempsky** [comment]
Closing since I don't think this is a gocode bug.  If we're not able to fix the upstream issue for 1.7, I'll reopen to look for a workaround.

**Comment by danp** [comment]
Thanks!

**Comment by mdempsky** [comment]
No problem, thanks for the report! :)
