### ISSUE TITLE
Problems with gb-based repositories.

### ISSUE THREAD

**Issue by nsf** [mdempsky/gocode#20]
Not quite sure why it happens. But on all of my gb-based code base I get this when running `gocode -s -debug`:

```
panic: inconsistent import:
        const net/http.StatusUnauthorized untyped int
previously imported as:
        const StatusUnauthorized untyped int
```

And similar messages for standard lib types. Maybe it has something to do with vendoring? I don't know. Have no reproducable test case yet. Will drop a note here when I do.

But maybe you have some ideas where it may come from?

**Comment by mdempsky** [comment]
Sorry no ideas off hand. But I'd be very interested in steps to reproduce it myself.

**Comment by nsf** [comment]
Oh, since message comes with a stack trace, I'll drop it here also, not sure if it's useful or not. Sadly can't share the source where I'm getting that error. But I'll try to reduce it to small reproducable case.

Full panic message with stacktrace:

```
panic: inconsistent import:
        var net/http.DefaultTransport net/http.RoundTripper
previously imported as:
        var DefaultTransport net/http.RoundTripper


goroutine 35 [running]:
runtime/debug.Stack(0xb, 0xc420a50430, 0x1)
        /home/nsf/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
        /home/nsf/go/src/runtime/debug/stack.go:16 +0x22
main.(*Server).AutoComplete.func1(0xc420130a40)
        /home/nsf/waytogo/src/github.com/mdempsky/gocode/server.go:68 +0x9e
panic(0x7f81e0, 0xc420a48c50)
        /home/nsf/go/src/runtime/panic.go:458 +0x243
go/types.(*Checker).handleBailout(0xc4201980e0, 0xc420a513b8)
        /home/nsf/go/src/go/types/check.go:213 +0xae
panic(0x7f81e0, 0xc420a48c50)
        /home/nsf/go/src/runtime/panic.go:458 +0x243
go/internal/gcimporter.(*importer).declare(0xc4201889c0, 0xa816c0, 0xc42085d4f0)
        /home/nsf/go/src/go/internal/gcimporter/bimport.go:175 +0x17c
go/internal/gcimporter.(*importer).obj(0xc4201889c0, 0xfffffffffffffffc)
        /home/nsf/go/src/go/internal/gcimporter/bimport.go:195 +0x1b4
go/internal/gcimporter.BImportData(0xc42012ea80, 0xc420b7c000, 0x1cdff0, 0x1ffe00, 0xc4201326e1, 0x8, 0x0, 0x8, 0x0, 0x1200000000)
        /home/nsf/go/src/go/internal/gcimporter/bimport.go:88 +0x390
go/internal/gcimporter.Import(0xc42012ea80, 0xc4201326e1, 0x8, 0xc4201fcc80, 0x34, 0xc420361540, 0x0, 0x0)
        /home/nsf/go/src/go/internal/gcimporter/gcimporter.go:166 +0x551
go/importer.gcimports.ImportFrom(0xc42012ea80, 0xc4201326e1, 0x8, 0xc4201fcc80, 0x34, 0x0, 0x8, 0xc41ffc0822, 0xc420a50b00)
        /home/nsf/go/src/go/importer/importer.go:70 +0x67
github.com/mdempsky/gocode/gbimporter.(*importer).ImportFrom(0xc42012a600, 0xc4201326e1, 0x8, 0xc4201fcc80, 0x34, 0x0, 0x0, 0x0, 0x0)
        /home/nsf/waytogo/src/github.com/mdempsky/gocode/gbimporter/gbimporter.go:82 +0x35d
go/types.(*Checker).collectObjects(0xc4201980e0)
        /home/nsf/go/src/go/types/resolver.go:191 +0x826
go/types.(*Checker).checkFiles(0xc4201980e0, 0xc42020f260, 0x3, 0x4, 0x0, 0x0)
        /home/nsf/go/src/go/types/check.go:225 +0xaa
go/types.(*Checker).Files(0xc4201980e0, 0xc42020f260, 0x3, 0x4, 0xc4202105d0, 0xc42018f440)
        /home/nsf/go/src/go/types/check.go:218 +0x49
go/types.(*Config).Check(0xc420212600, 0x0, 0x0, 0xc42012a640, 0xc42020f260, 0x3, 0x4, 0xc4201fed20, 0x0, 0xc42018f528, ...)
        /home/nsf/go/src/go/types/api.go:344 +0x1a3
github.com/mdempsky/gocode/suggest.(*Config).analyzePackage(0xc420a519c8, 0xc42012c190, 0x48, 0xc42019c000, 0x3c9c, 0x3c9c, 0x394, 0x8, 0x6, 0x0)
        /home/nsf/waytogo/src/github.com/mdempsky/gocode/suggest/suggest.go:107 +0x6f0
github.com/mdempsky/gocode/suggest.(*Config).Suggest(0xc420a519c8, 0xc42012c190, 0x48, 0xc42019c000, 0x3c9c, 0x3c9c, 0x394, 0xc420184300, 0x56, 0x0, ...)
        /home/nsf/waytogo/src/github.com/mdempsky/gocode/suggest/suggest.go:32 +0xb5
main.(*Server).AutoComplete(0xabea70, 0xc4201881a0, 0xc420130a40, 0x0, 0x0)
        /home/nsf/waytogo/src/github.com/mdempsky/gocode/server.go:93 +0x1bf
reflect.Value.call(0xc420154300, 0xc42013e040, 0x13, 0x8915b0, 0x4, 0xc420a51ec0, 0x3, 0x3, 0x412d78, 0x0, ...)
        /home/nsf/go/src/reflect/value.go:434 +0x5c8
reflect.Value.Call(0xc420154300, 0xc42013e040, 0x13, 0xc420a51ec0, 0x3, 0x3, 0x9, 0x9, 0x1000)
        /home/nsf/go/src/reflect/value.go:302 +0xa4
net/rpc.(*service).call(0xc420136380, 0xc420136180, 0xc420132070, 0xc420146200, 0xc4201300c0, 0x7e47c0, 0xc4201881a0, 0x16, 0x7e4780, 0xc420130a40, ...)
        /home/nsf/go/src/net/rpc/server.go:383 +0x148
created by net/rpc.(*Server).ServeCodec
        /home/nsf/go/src/net/rpc/server.go:477 +0x421
```

**Comment by nsf** [comment]
The stack trace is from a different place, but you can see the pattern, it's always about "inconsistent import". And stack trace shows indeed that gb importer is triggered.

**Comment by nsf** [comment]
Interesting, the panic is also triggered on a repo without binary gb packages. E.g.

```
[nsf @ aaa]$ tree -L 1
.
├── src
└── vendor

2 directories, 0 files
```

Starting to shrink it down to find the reason...

**Comment by nsf** [comment]
Oh, never mind that comment about binary packages, vendor dir has it's own "pkg".

**Comment by nsf** [comment]
That above about vendor dir and "pkg" was also false, stale files from go tool. Lots of stale files.

Yeah, I don't know what's going on. Removed stale packages in GOPATH, in fact I removed GOPATH/pkg completely. Now it doesn't panic, but I also don't see some of the imports I use (after running gb build).

Here's a reproducable case for you.
1. Create dir structure:
   
   ```
   [nsf @ gobug]$ tree src/
   src/
   └── mypkg
       └── main.go
   
   1 directory, 1 file
   ```
2. `main.go` contents:
   
   ``` go
   package mypkg
   
   import "github.com/jinzhu/gorm"
   
   func main() {
       var _ gorm.DB
   }
   ```
3. Fetch dependency: `gb vendor fetch github.com/jinzhu/gorm`.
4. Build the repo:
   
   ```
   [nsf @ gobug]$ gb build
   github.com/jinzhu/inflection
   github.com/jinzhu/gorm
   mypkg
   ```
5. All good, here's the pkg tree:
   
   ```
   [nsf @ gobug]$ tree pkg/
   pkg/
   └── linux-amd64
       ├── github.com
       │   └── jinzhu
       │       ├── gorm.a
       │       └── inflection.a
       └── mypkg.a
   
   3 directories, 3 files
   ```
6. Try autocompletion:
   
   ```
   [nsf @ gobug]$ gocode -in src/mypkg/main.go autocomplete src/mypkg/main.go 79
   Found 1 candidates:
   func main()
   ```

No package in output. Also to reproduce that behaviour make sure $GOPATH/pkg doesn't exist.

Gocode's debug output:

```
2016/09/18 00:15:47 Got autocompletion request for '/home/nsf/tmp/gobug/src/mypkg/main.go'
2016/09/18 00:15:47 Cursor at: 79
2016/09/18 00:15:47 -------------------------------------------------------
package mypkg

import "github.com/jinzhu/gorm"

func main() {
        var _ gorm.DB
}
#
2016/09/18 00:15:47 -------------------------------------------------------
2016/09/18 00:15:47 Error parsing input file (outer block):
2016/09/18 00:15:47  /home/nsf/tmp/gobug/src/mypkg/main.go:8:1: expected declaration, found ';'
2016/09/18 00:15:47 Elapsed duration: 393.209µs
2016/09/18 00:15:47 Offset: 0
2016/09/18 00:15:47 Number of candidates found: 1
2016/09/18 00:15:47 Candidates are:
2016/09/18 00:15:47   func main()
2016/09/18 00:15:47 =======================================================
```

---

And lastly.. My version of gocode yields this on the same dir:

```
[nsf @ gobug]$ gocode -in src/mypkg/main.go autocomplete src/mypkg/main.go 79
Found 2 candidates:
  func main()
  package gorm
```

**Comment by stamblerre** [comment]
The go/packages-based gocode (https://github.com/stamblerre/gocode) or the eventual go/packages-based LSP implementation will hopefully solve these problems once there is a gb driver for go/packages. I don't think we will work on this further.
