### ISSUE TITLE
expected selector or type assertion, found ';'

### ISSUE THREAD

**Issue by fhmily** [mdempsky/gocode#61]
https://github.com/jinzhu/gorm is a orm library for golang, using this library require implementing from it's gorm.Model and gocode failed with that.

sample code (go build with no problem):

```
package main

import (
	"github.com/jinzhu/gorm"
)

type T struct {
	gorm.Model

	X string
}

func main() {
	t := T{}
	t.X = "abc"
}

```

error log from gocode:

```
2018/09/17 23:04:41 -------------------------------------------------------
package main

import (
	"github.com/jinzhu/gorm"
)

type T struct {
	gorm.Model

	X string
}

func main() {
	t := T{}
	t.X = "abc"
	t.#
}
2018/09/17 23:04:41 -------------------------------------------------------
2018/09/17 23:04:41 Error parsing input file (outer block):
2018/09/17 23:04:41  /Users/xxxxx/go/src/bitbucket.org/xxxx/xxxx/test.go:16:4: expected selector or type assertion, found ';'
goroutine 50 [running]:
runtime/debug.Stack(0xb, 0xc000211200, 0x1)
	/usr/local/Cellar/go/HEAD-43f54c8/libexec/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
	/usr/local/Cellar/go/HEAD-43f54c8/libexec/src/runtime/debug/stack.go:16 +0x22
main.(*Server).AutoComplete.func1(0xc000202640)
	/Users/jackwang/.vim/plugged/YouCompleteMe/third_party/ycmd/third_party/gocode/server.go:71 +0x94
panic(0x142bbc0, 0x1551820)
	/usr/local/Cellar/go/HEAD-43f54c8/libexec/src/runtime/panic.go:513 +0x1b9
github.com/mdempsky/gocode/lookdot.walk(0x1556980, 0xc0001fa930, 0xc0001f0101, 0xc0002117d0)
	/Users/jackwang/go/src/github.com/mdempsky/gocode/lookdot/lookdot.go:77 +0xaec
github.com/mdempsky/gocode/lookdot.Walk(0xc000211830, 0xc0002117d0, 0x87)
	/Users/jackwang/go/src/github.com/mdempsky/gocode/lookdot/lookdot.go:12 +0xd2
github.com/mdempsky/gocode/suggest.(*Config).Suggest(0xc000211a70, 0xc000222000, 0x37, 0xc000224000, 0x89, 0x89, 0x86, 0x14760a0, 0xc00005ea88, 0xc00005eb80, ...)
	/Users/jackwang/go/src/github.com/mdempsky/gocode/suggest/suggest.go:45 +0x58f
main.(*Server).AutoComplete(0x1885620, 0xc0001fc0d0, 0xc000202640, 0x0, 0x0)
	/Users/jackwang/.vim/plugged/YouCompleteMe/third_party/ycmd/third_party/gocode/server.go:102 +0x215
reflect.Value.call(0xc0000b6360, 0xc0000b4550, 0x13, 0x14d37c8, 0x4, 0xc00005ef18, 0x3, 0x3, 0xc0001f8040, 0x0, ...)
	/usr/local/Cellar/go/HEAD-43f54c8/libexec/src/reflect/value.go:447 +0x450
reflect.Value.Call(0xc0000b6360, 0xc0000b4550, 0x13, 0xc000166718, 0x3, 0x3, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/HEAD-43f54c8/libexec/src/reflect/value.go:308 +0xa4
net/rpc.(*service).call(0xc0000a98c0, 0xc00013e000, 0xc0000a7878, 0xc0000a7890, 0xc0000e2200, 0xc0000bcc40, 0x1417d00, 0xc0001fc0d0, 0x16, 0x1417cc0, ...)
	/usr/local/Cellar/go/HEAD-43f54c8/libexec/src/net/rpc/server.go:384 +0x14e
created by net/rpc.(*Server).ServeCodec
	/usr/local/Cellar/go/HEAD-43f54c8/libexec/src/net/rpc/server.go:481 +0x47e
```

**Comment by sooth-sayer** [comment]
👍

**Comment by gencer** [comment]
Have the same issue. Lets say I have a code like this:

```
    exists, err := models.Files(
		And("is_deleted IS FALSE"),
	).One(db)

	if err != nil {
		return nil, err
	}
    return exists, nil
```

And let's say I want to add a line between error check and entity check.

```
    ...
	).One(db)
    
    exists. # <-- after dot I expect to be feed by possible values, however I get an error. See below.
    
	if err != nil {
    ...
```

Error is:
```
2018/11/03 14:51:04 -------------------------------------------------------
2018/11/03 14:51:04 Error parsing input file (outer block):
2018/11/03 14:51:04  d:\Go\src\distributer\main.go:593:7: expected selector or type assertion, found ';'
2018/11/03 14:51:04  d:\Go\src\distributer\main.go:594:2: expected ';', found 'if'
2018/11/03 14:51:04 Elapsed duration: 83.0192ms
2018/11/03 14:51:04 Offset: 0
2018/11/03 14:51:04 Number of candidates found: 0
2018/11/03 14:51:04 Candidates are:
2018/11/03 14:51:04 =======================================================
```

At this point, not just this line but every autocomplete feature stops working. Nothing auto-completes anymore. After await 3-5 minutes, it fixes itself but if I add any line to anywhere it goes again.

**Comment by gencer** [comment]
@mdempsky any update or comment? See also #59. Exactly happening.

tested against Go1.11.2 and go1.10.5

Any recommendation?

**Comment by stamblerre** [comment]
@gencer: this issue does not seem related to the one mentioned above. It seems like you are having other problems with gocode, as we've discussed in https://github.com/mdempsky/gocode/issues/84. Let's follow up there.

**Comment by stamblerre** [comment]
Confirmed that I can no longer reproduce @fhmily's issue.
